name: Terraform Apply

on:
  push:
    branches: [main]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Debug GCP_SA_KEY Secret
        run: |
          if [[ -z "${{ secrets.GCP_SA_KEY }}" ]]; then
            echo "ERROR: GCP_SA_KEY is empty or not set!"
            exit 1
          else
            echo "GCP_SA_KEY is set. Length: $(echo -n "${{ secrets.GCP_SA_KEY }}" | wc - c) characters"
          fi

      - name: Authenticate GCP
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 > $HOME/.gcp-key.json
          gcloud auth activate-service-account --key-file=$HOME/.gcp-key.json
          gcloud config set project ${{secrets.GCP_PROJECT_ID }}

        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

      - name: Initialize Terraform
        run: terraform init
        env:
          GOOGLE_APPLICATION_CREDENTIOALS: $HOME/.gcp-key.json

      - name: Plan Terraform changes
        run: terraform plan
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/.gcp-key.json

      - name: Apply Terraform changes
        run: terraform apply -auto-approve
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/.gcp-key.json
