name: Terraform Apply

on:
  push:
    branches: [main]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Authenticate to GCP using Base64-Decoded Credentials
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > /home/runner/.gcp-key.json
          ls -lah /home/runner/.gcp-key.json           
          cat /home/runner/.gcp-key.json | jq .       
          gcloud auth activate-service-account --key-file=/home/runner/.gcp-key.json           
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }} 
      - name: Initialize Terraform
        run: terraform init
        env:
          GOOGLE_APPLICATION_CREDENTIOALS: $HOME/.gcp-key.json

      - name: Plan Terraform changes
        run: terraform plan
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/.gcp-key.json

      - name: Apply Terraform changes
        run: terraform apply -auto-approve
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/.gcp-key.json
