name: Terraform Apply

on:
  push:
    branches: [main]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Authenticate GCP
        run:
          echo "${{ secrets.GCP_SA_KEY }}" > ~/.gcp-key.json
          gcloud auth activate-service-account --key-file=$HOME/.gcp-key.json
          gcloud config set project ${{secrets.GCP_PROJECT_ID }}
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform changes
        run: terraform plan
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ~/.gcp-key.json

      - name: Apply Terraform changes
        run: terraform apply -auto-approve
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ~/.gcp-key.json
